# A bunch of build steps
# TODO:
#   [ ] Configure build order: https://cloud.google.com/cloud-build/docs/configuring-builds/configure-build-step-order
#   [ ] Only run yarn steps if Node.js changes
#   [ ] Add URL checkers
#   [ ] Coverage check
steps:
# Git Presubmit Linter
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/google/git-presubmit-linter.git']
  id: 'Download Git Presubmit Linter'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', 'git log -1 --pretty=%B | ./git-presubmit-linter/rules/verb-tense.sh imperative']
  id: 'Check git message verb tense'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', 'git log -1 --pretty=%B | ./git-presubmit-linter/rules/line-length.sh 80']
  id: 'Check git message line length'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', 'git diff HEAD~1 --pretty=%B | ./git-presubmit-linter/rules/trailing-whitespace.sh']
  id: 'Check commit no trailing whitespace'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', './git-presubmit-linter/tools/changelog.sh > changelog.txt']
  id: 'Generate changelog'
# Yarn
- name: 'gcr.io/cloud-builders/yarn'
  args: ['']
  id: 'Install dependencies'
- name: 'gcr.io/cloud-builders/yarn'
  args: ['lint']
  id: 'Lint'
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
  id: 'Build'
- name: 'gcr.io/cloud-builders/yarn'
  args: ['test']
  id: 'Test'
- name: 'gcr.io/cloud-builders/yarn'
  args: ['docs']
  id: 'Docgen'
- name: 'gcr.io/cloud-builders/yarn'
  args: ['package']
  id: 'Generate archive'
- name: 'ubuntu'
  args: ['tar', '-tf', '*.tgz', '|', './git-presubmit-linter/tools/filelist.sh', './script/package.txt']
  id: 'Verify archive contents'
artifacts:
  objects:
    location: 'gs://fleker-actions-on-googl-lib/$SHORT_SHA'
    paths: ['changelog.txt', 'docs/']
